[[assets]]
name = "Bitcoin"
url = "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=eur"
price_path = "bitcoin.eur"
unit = "EUR"
poll_interval = "1m"

[[assets]]
name = "Gold"
url = "https://xaus.com/api/v1/spot?currency=EUR"
price_path = "xau.price"
unit = "EUR"
poll_interval = "1h"

[[assets]]
name = "Gas"
url = "https://eurooilwatch.com/api/v1/gas"
price_path = "ttf.priceEurMwh"
unit = "EUR"
poll_interval = "24h"
